class Setting {
  static const languages = {
    "en": {"name": "English", "flag": "🇬🇧"},
    "fa": {"name": "Persian", "flag": "🇮🇷"},
    "nl": {"name": "Dutch", "flag": "🇳🇱"},
    "de": {"name": "German", "flag": "🇩🇪"},
    "zh": {"name": "Chinese", "flag": "🇨🇳"},
    "es": {"name": "Spanish", "flag": "🇪🇸"},
    "fr": {"name": "French", "flag": "🇫🇷"},
    "ar": {"name": "Arabic", "flag": "🇸🇦"},
    "it": {"name": "Italian", "flag": "🇮🇹"},
    "ru": {"name": "Russian", "flag": "🇷🇺"},
    "tr": {"name": "Turkish", "flag": "🇹🇷"},
    "ja": {"name": "Japanese", "flag": "🇯🇵"},
    "ko": {"name": "Korean", "flag": "🇰🇷"},
    "pt": {"name": "Portuguese", "flag": "🇵🇹"},
    "hi": {"name": "Hindi", "flag": "🇮🇳"},
    "sv": {"name": "Swedish", "flag": "🇸🇪"},
    "no": {"name": "Norwegian", "flag": "🇳🇴"},
    "da": {"name": "Danish", "flag": "🇩🇰"},
    "fi": {"name": "Finnish", "flag": "🇫🇮"},
    "pl": {"name": "Polish", "flag": "🇵🇱"},
    "cs": {"name": "Czech", "flag": "🇨🇿"},
    "he": {"name": "Hebrew", "flag": "🇮🇱"},
    "th": {"name": "Thai", "flag": "🇹🇭"},
  };
}
